### ISSUE TITLE
Cobaya chain reading

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#129]
I don't think as it stands that `MCMCSamples` can read [cobaya](https://cobaya.readthedocs.io) formatted chains. @lukashergt -- as a cobaya user have you found a workaround for this? Am I wrong in thinking that a `anesthetic.read.cobaya` submodule is needed in order to do this?

**Comment by lukashergt** [comment]
Yes, I've got my own branch for handling Cobaya MCMC chains. The difficulty lies in working with the `.yaml` input file instead of having `.paramnames` and `.ranges` files. However, there is a discrepancy in the number of columns between raw PolyChord output and Cobaya output that I haven't fully chased down. It works for the sampling and most derived parameters, but Cobaya seems to calculate additional derived parameters on top of what is specified in a `.yaml` file. This makes my Cobaya reader more of a hack than a fully working branch, which is why I didn't create a PR for it, yet.

Making a proper PR for this and also for updating the MontePython reader is on my TODO list, but not sufficiently high priority at the moment, since I have my own working, albeit hacky, version.

**Comment by williamjameshandley** [comment]
>Yes, I've got my own branch for handling Cobaya MCMC chains

I suspected as much. This is good -- there is no rush, but it would be good for it to implemented at some point when you are less busy. Just wanted to confirm my suspicions so that I don't re-invent the wheel.

**Comment by williamjameshandley** [comment]
As @Stefan-Heimersheim is implementing a dynesty interface in #158, it might be worth reviving this at the same time (since I imagine APIs will be similar).
