### ISSUE TITLE
Merging models with evidence weighting

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#135]
Does anesthetic have a function to merge datasets (`NestedSamples`) _with weights per dataset_?

**Is your feature request related to a problem? Please describe.**
When considering multiple models for an inference, such as the [FlexKnot reionization model by Millea&Bouchet](https://arxiv.org/pdf/1804.08476.pdf), one want's to marginalize over different models, i.e. average the constraints weighted with the model's evidence. [fgivenx](https://fgivenx.readthedocs.io/en/latest/fgivenx.html#fgivenx.drivers.plot_contours) seems to support such options, does `anesthetic` have a similar function?

**Describe the solution you'd like**
A function that merges multiple sets of `NestedSamples`, using the evidence Z (or provided weighting), or a way to directly plot posteriors using multiple sets of samples with weights.

**Describe alternatives you've considered**
One could change the weights manually and use the `merge` function to merge the samples. This is straightforward after converting to MCMCSamples, but I'm not sure about the implications for NestedSamples.

**Additional Context**
This is not urgent or necessary for my work now (I can convert to MCMCSamples and do it manually) but since fgivenx does have the functionality it might be easy (?) to implement and nice to have here :)

**Comment by williamjameshandley** [comment]
Hi @Stefan-Heimersheim. This has been functionality that I've been intending to add for a while, as it would be very helpful for a project I'm doing with @tmcaloone. 

At the moment, I'm only 3/4 clear on the theory of how to solve the general problem (which we can also discuss if you're interested), which is to take several sets of `NestedSamples`, and produce a new set of `NestedSamples` (with evidence calculations etc) as if you had been sampling over the likelihoods simultaneously. However, I'm not sure this is even exactly what you want in this case, since it would end up discarding a lot of samples.

If I understand correctly, the following should do what you want it to

```python
import numpy as np
from scipy.special import logsumexp
from anesthetic import NestedSamples, MCMCSamples

samples_1 = NestedSamples(root='tests/example_data/pc')
samples_2 = NestedSamples(root='tests/example_data/pc_250')

samples = [samples_1, samples_2]
logZs = np.array([s.logZ() for s in samples])
logZs -= logsumexp(logZs)
Zs = np.exp(logZs)

samps = MCMCSamples()
for s, Z in zip(samples, Zs):
    weights = s.weights / s.weights.sum() * Z
    s = MCMCSamples(s, weights=weights)
    samps = samps.append(s)
```

If this is what you are after, please could you submit it as a PR so that other users can benefit as well?

**Comment by Stefan-Heimersheim** [comment]
Ah you are right, I would not need the output to be `NestedSamples` so it can be implemented quite simple as you suggested and I think I can write a PR.

Where would be best to implement it? I think as a method of `NestedSamples` would be confusing since it also works for just an MCMC sample with a logZ / global weighting (but `MCMCSamples` would be confusing too). Maybe just somewhere in `anesthetic.utils`?

**Comment by Stefan-Heimersheim** [comment]
To follow up this is my current idea (not tested yet), is the convention in anesthetic usually to make max(weights)==1? Then I would add that as well.

```python
def merge_samples_weighted(samples, weights=None):
    r"""Merge a list of samples weighting each with a given
    weight or its Bayesian evidence (exp(logZ)).

    samples can be NestedSamples or MCMCSamples, in the former
    case weights can be omitted and exp(logZ) is used instead.

    Returns an MCMCSamples object containing the weighted
    """
    mcmc_samples = [MCMCSamples(s) for s in samples]
    if weights==None:
        logZs = np.array([s.logZ() for s in samples])
        # Subtract logsumexp to avoid numerical issues (similar to max(logZs))
        logZs -= logsumexp(logZs)
        weights = np.exp(logZs)

    new_samples = MCMCSamples()
    for s, w in zip(samples, weights):
        new_weights = s.weights / s.weights.sum() * w
        s = MCMCSamples(s, weights=weights)
        new_samples = new_samples.append(s)

    # Should we make sure that max(new_samples.weights)==1 or some other normalization?

    return new_samples
```

**Comment by williamjameshandley** [comment]
Nice -- this looks like exactly the kind of interface we're after. I also like the optional weights element.. Better to discuss code details in a pull request, but to get that started I would suggest putting it in `anesthetic/samples.py`, since that where the `merge_nested_samples` function goes at the moment. Whether or not that's precisely the right place going forward is less important than consistency when adding functionality.
