### ISSUE TITLE
Behavior of live_points

### ISSUE THREAD

**Issue by yallup** [williamjameshandley/anesthetic#160]
# Context:
I was trying to make a "static" version of anesthetic.gui, i.e make a gif of the live point evolution by taking live point sample snapshots when progressing uniformly through the logL (this may or may not be the best way of doing this). In doing this I found the fact that the live_points method returns a weighted dataframe to be maybe a bit unintuitive to me.

## MWE:
```python
from anesthetic import NestedSamples
import numpy as np
df=NestedSamples(root='./example_data/pc_250')
n_frames=10
for i in np.arange(0,n_frames+1,1):
    cset=df.logL_birth[~(df.logL_birth == -np.inf)]
    points = df.live_points(cset.min() + (i) / n_frames * (cset.max() - cset.min()))
    f,a=points.plot_2d(["x0","x1"],types={'lower': 'scatter'})
    f.show()
```

 
![image](https://user-images.githubusercontent.com/6486664/119821242-3b36bd80-beea-11eb-972e-6aa4f25f6703.png)

So my understanding is that I'm basically calling ```points.compress()``` and plotting a scatter of what's left.

In some more extreme examples I was trying to run (which I can supply input ns chains for, although they are large), the early frames can be entirely composed of 0 weight points so can't be drawn. If I can ```df.live_points(cset.min())``` where ```cset.min()``` is the lowest finite logL_birth contour I get a frame of 0.0 weight points

# Proposal
My intuition may be wrong here but I would naively expect live points to not be weighted by the posterior, if I include something hacky like:
```python
points = df.live_points(cset.min() + (i) / n_frames * (cset.max() - cset.min()))
points.weights = np.ones_like(points.weights)
f,a=points.plot_2d(["x0","x1"],types={'lower': 'scatter'})
```
then the same frame as before becomes
![image](https://user-images.githubusercontent.com/6486664/119823607-f3fdfc00-beec-11eb-811c-0ebd45766e35.png)

and the evolution through the frames looks qualitatively at least like what I would expect. My NS fundamentals may not be great so comments if what I am doing don't make sense are welcome!

EDIT: the actual solution I'd imagine is at least having an option to return a dataframe over a weighteddataframe rather than just squashing the weights like this

**Comment by appetrosyan** [comment]
> My intuition may be wrong here but I would naively expect live points to not be weighted by the posterior,

I've had a similar issue with `paranestamol`, during a live demonstration to @williamjameshandley . The weighting needs to be manually disabled with the "hack", that you mentioned.

**Comment by williamjameshandley** [comment]
I agree that it is 'less surprising' for these to be equally weighted samples. I would vote that they should probably be a set of unit weight `MCMCSamples`, rather than `NestedSamples`, as dropping down to a `pd.DataFrame` would lose common plotting functionality which users might expect.

I also think that at the moment the convention of what `samples.live_points(0)` returns is not very intuitive. I think that this should give the live points 'at iteration 0', i.e. the original set, but in fact they give the live points after the first point has been deleted.

I think only one line of code needs to be changed, however, having just had a go at this, the tests fail on the wedding cake example, which does assume
