### ISSUE TITLE
2d kde plots can be much wider than actual distribution / samples (over-smoothing?)

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#165]
**Describe the bug**
The contours from `plot_2d` are very large / over-smoothed if the PDF is very peaked/asymmetric (see example below). Not sure if this is a bug, I guess it would rather be a `scipy` bug, but should we do something about it?

**To Reproduce**
I uploaded some [example data](http://www.ast.cam.ac.uk/~sh2061/data.zip) where the problem occurs, the data files are currently available at `http://www.ast.cam.ac.uk/~sh2061/xdata.npy` etc.
```python
x = np.load("xdata.npy")
y = np.load("ydata.npy")
samples = anesthetic.MCMCSamples(np.array([x,y]).T, columns=['x','y'])
samples.limits={}
fig, axes = samples.plot_2d(['x','y'], types={"lower": "kde"})
samples.plot_2d(axes, types={"lower": "scatter"}, ncompress=2000)
```
These samples are sampled from a flat prior in model parameter, but the points show some derived parameters.
For these derived parameters (usually `samples['x']=function(samples)` the `limits` are not set by default. In many "less rectangular" cases `limits` don't help though, like this one:
```python
    x = np.load("xdata2.npy")
    y = np.load("ydata2.npy")
    samples = anesthetic.MCMCSamples(np.array([x,y]).T, columns=['x','y'])
    #samples.limits={}
    fig, axes = samples.plot_2d(['x','y'], types={"lower": "kde"})
    samples.plot_2d(axes, types={"lower": "scatter"}, ncompress=2000)
```

**Expected behavior**
A cutoff where the data is cut off, or close to it. Especially at the bottom 95 close to 68% contour lines. This can only be partially fixed with setting the `limits` dictionary.

I see that those samples have a rather difficult distribution. If this cannot be fixed, do you think it would be possible to have a warning in some way to make sure the user notices that the kde contours look very misleading? I guess always plotting the scatter plot (as anesthetic does by default) helps with noticing such problems.

**Screenshots**
This is what happens using the `kde` plot (first example)
![xydemo_kde](https://user-images.githubusercontent.com/40799217/120451901-b9331280-c389-11eb-8e65-049e9ce682a6.png)
2nd data set. Adding `ncompress` up to `10000` does not help.
![xydemo2_kde](https://user-images.githubusercontent.com/40799217/120451886-b6382200-c389-11eb-9e72-39644a429b83.png)
FastKDE can help sometimes:
![xydemo2fastkde](https://user-images.githubusercontent.com/40799217/120451936-c18b4d80-c389-11eb-9f7f-8221b1887892.png)
But not always:
![xydemo_fastkde](https://user-images.githubusercontent.com/40799217/120451912-bcc69980-c389-11eb-9b32-fa5e6b0992bb.png)
This is an example plotting the same data (first set) with `GetDist`:
![getdist](https://user-images.githubusercontent.com/40799217/120453807-41fe7e00-c38b-11eb-95eb-0cfdcf404be7.png)

**Additional context**
I checked
* Higher values of `ncompress` up to `10000` without visible change
* `fastkde` sometimes works, but produces rather jagged contours (sometimes quite unreadable)
* Setting the scalar `bw_method` [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) for `kde` to values between 1e-5 and 1e5 but that seems to have no effect

**Edit:** I noticed I didn't try high enough values of `ncompress` (I thought it was getting super slow but with FastKDE it actually is okay), and setting `ncompress=3200000` (which is the size of my sample set) produces plots somewhat similar to GetDist
![Figure_1](https://user-images.githubusercontent.com/40799217/121063053-c141e680-c7bd-11eb-93d2-8395ca62cdda.png)

**Comment by lukashergt** [comment]
Hi @Stefan-Heimersheim, 

sorry for taking so long to look at this. Thanks for the reproducable example. This addresses the issue of finding the optimal bandwith for the KDE, which is not easy to do in an automated fashion.

> This can only be partially fixed with setting the `limits` dictionary.

> Adding `ncompress` up to `10000` does not help.

Hmm, for me the combination of `limits` with higher `ncompress` looks quite good:

```python
import numpy as np
import anesthetic

x = np.load("xdata.npy")
y = np.load("ydata.npy")
samples = anesthetic.MCMCSamples(np.array([x,y]).T, columns=['x','y'])
samples.limits={}
samples.limits['x'] = (None, samples.x.max())
samples.limits['y'] = (samples.y.min(), None)

fig, axes = samples.plot_2d(['x','y'], types={"lower": "kde"}, ncompress=10000)
samples.plot_2d(axes, types={"lower": "scatter"}, ncompress=2000)
axes.iloc[0, 0].set_xlim(8, 13)
axes.iloc[0, 0].set_ylim(-1, 4)
```

![image](https://user-images.githubusercontent.com/18258042/122601381-108ddf80-d026-11eb-9630-99d808b4c6d5.png)

I find this arguably better than the GetDist output, which in my opinion reduces the bandwith too far (it still looks ok because our eyes iron out the raggedy contour edges, but in a 1D plot we would call that out for being overfitted, I think).

You can improve on the above plot by further cranking up to `ncompress=30000`:

![image](https://user-images.githubusercontent.com/18258042/122601245-d7556f80-d025-11eb-8039-bfefd65f2459.png)

Cranking up `ncompress` does indeed slow down the computation. I'm getting 7s for `ncompress=10000` and 23s for `ncompress=30000`. I think that is acceptable for publishing-quality plots. When your just exploring, then you don't need that high `ncompress` to see what's going on, I think, right? Plus, for exploration you can always include the scatter plot...

@williamjameshandley Did you ever consider/look into attempts at parallelising this to speed up computation? Could that be something helpful to get a speed-up of a few?

**Comment by lukashergt** [comment]
As for your second plotting example, I get the following:

```python
x = np.load("xdata2.npy")
y = np.load("ydata2.npy")
samples = anesthetic.MCMCSamples(np.array([x,y]).T, columns=['x','y'])
samples.limits={}
samples.limits['x'] = (samples.x.min(), samples.x.max())
samples.limits['y'] = (samples.y.min(), None)
fig, axes = samples.plot_2d(['x','y'], types={"lower": "kde"}, ncompress=50000)
samples.plot_2d(axes, types={"lower": "scatter"}, ncompress=2000)
```

![image](https://user-images.githubusercontent.com/18258042/122603716-a4ad7600-d029-11eb-83ef-a548b9e03d0b.png)

I think the problem here is less one of bandwidth, but rather that this is a quite difficult case, because there seems to be a non-linear line excluding part of the parameter space, right?

@williamjameshandley Do you reckon there could might be a way of telling anesthetic about prior excluded regions and have it cut them off similar to how it's doing it at the moment using `limits`? A potentially simpler case would be a linear line, but a curved line might not be that much more difficult?

**Comment by Stefan-Heimersheim** [comment]
In all of the plots you show I find the contours still a bit problematic. Looking at the very left edge, or the part just above (8.5 , 0) in the 3rd plot you see a region without any samples but the 68% contour still goes way into that region. I think this is my main issue, there is a clear cutoff and we are not capturing it.

![screenshot_2021-06-18_23-43-37](https://user-images.githubusercontent.com/40799217/122621953-06ec9200-d08f-11eb-8ad3-62f1d23a996f.png)

I acknowledge of course that this is not necessarily the job of the plotting tool and more of the researcher to make sure they use their tools correctly / check what they do; I just noticed it and was surprised.

---

In my toy data, the 2nd data set is just a transformed version of the 1st one, so in this case one could calculate the analytic cut-off, but the lower cutoff e.g. is not manually imposed but by the simulation (temperature of radiation, where the lower limit is T_cmb).

> @williamjameshandley Do you reckon there could might be a way of telling anesthetic about prior excluded regions and have it cut them off similar to how it's doing it at the moment using limits? A potentially simpler case would be a linear line, but a curved line might not be that much more difficult?

I'm not Will but from my side I don't think that would be very helpful in too many cases. I think in most such cases you won't know the cut-off, and fitting a function to the use it for the cutoff also seems like not a good idea. Maybe automatically assuming `limits=[min(data), max(data)]` when plotting parameters with no limit information might help (as in my case, there were no limits as I used derived parameters but simple limits already helped a lot.

**Comment by lukashergt** [comment]
> Looking at the very left edge, or the part just above (8.5 , 0) in the 3rd plot you see a region without any samples but the 68% contour still goes way into that region. I think this is my main issue, there is a clear cutoff and we are not capturing it.

Well, I did not include the low-x limit, once you do that there is a bit of a cutoff. I'd be careful not to over-interpret the output from the scatter plot, though, that can be misleading in its own right. Maybe a KDE with 2 contours is not the best choice for this type of complicated distribution. If a high level of accuracy is needed here, then maybe it might be best to show the full histogram? 
```python
fig, axes = samples.plot_2d(['x','y'], types={"lower": "hist"}, bins=50)
```
![image](https://user-images.githubusercontent.com/18258042/122625633-1520bb00-d05b-11eb-962d-c4a9a2441074.png)

Looking at this I can see why the KDE picks up on a lower left "kink". You can also play around with `cmin` which leads me to believe that that kink is actually real...

---

> I think in most such cases you won't know the cut-off

Agreed, using a function would only help in cases like your lower curved line in the second example, where you know about the cutoff line. A more frequent case would be the identity line when e.g. one parameter is strictly smaller than the other, such as for the black hole masses in binary mergers with GW data.

---

> Maybe automatically assuming `limits=[min(data), max(data)]` when plotting parameters with no limit information might help

Anesthetic actually should already do that. If you remove the `samples.limits={}` line from your first example then anesthetic should automatically assign the limits.

**Comment by Stefan-Heimersheim** [comment]
> Anesthetic actually should already do that. If you remove the samples.limits={} line from your first example then anesthetic should automatically assign the limits.

Sorry I meant when you create a derived variable with `samples['c'] = samples['a']  + samples['b'] ` the limits do not get copied, so when you plot 'c' you get a plot without limits (that's what happened to me, my limits were on model parameters and the temperatures in my plot were derived)

**Comment by lukashergt** [comment]
> Maybe automatically assuming `limits=[min(data), max(data)]` when plotting parameters with no limit information might help

> Sorry I meant when you create a derived variable with `samples['c'] = samples['a'] + samples['b'] ` the limits do not get copied, so when you plot `'c'` you get a plot without limits 

That's a good suggestion. Tackled in #166. Surprisingly easy, just a one-liner: calling `self._set_automatic_limits()` at the start of `plot`.

**Comment by lukashergt** [comment]
@Stefan-Heimersheim Should I flag this issue as fixed by #166, or is there anything else that we should be discussing here?

Trying to summarize a bit w.r.t. the initial post, I'd say that the combination of correct limits (fixed by #166) and sufficiently high `ncompress` should in principle give correct results, albeit at the potential cost of rather slow computation (recommendation there could be to test things out with low `ncompress` and then give it more time with high `ncompress` for a publication plot?).

As regards the question of warning the user about difficult distributions, I don't see how one could implement such a warning. My general suggestion there would be to always explore multiple visualisation methods (`'kde'`, `'scatter'`, `'hist'`) before settling on one (or maybe a combination?) when dealing with complicated distributions.

**Comment by Stefan-Heimersheim** [comment]
Yes thanks a lot for the help & advice @lukashergt.

> My general suggestion there would be to always explore multiple visualisation methods ('kde', 'scatter', 'hist') before settling on one (or maybe a combination?) when dealing with complicated distributions.

One just has to keep this in mind and always should double-check nontrivial distributions.

I expect #166 will fix this for quite a few common cases, and the general problem isn't really solvable here in a simple way, so lets consider this fixed :)

**Comment by lukashergt** [comment]
> One just has to keep this in mind and always should double-check nontrivial distributions.

Agreed. Would probably be good for this recommendation to appear in Readme/documentation/demo somewhere, so I'll link #62 here.
