### ISSUE TITLE
contour levels and (e.g.) linestyles arguments use inverted ordering

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#169]
**Describe the bug**
`samples.plot_2d(paramNames, types={'lower':'fastkde'}, levels=[0.68, 0.95], linestyles=['dashed', 'dotted'])` unintuitively makes the **68%** contour line **dotted**, and the **95%** contour line **dashed**.

**To Reproduce**
MWE:
```python
import anesthetic
import matplotlib.pyplot as plt
import numpy as np

paramNames = ['a1','a2','a3','a4']
limits = {'a1':[0,1], 'a2':[0,1], 'a3':[0,1], 'a4':[0,1]}

np.random.seed(42)
a = np.random.normal(size=(1000,4), scale=0.1)
weights = 1-np.exp(-1/2*(a[:,2]**2+0.5*a[:,3]**2))

samples = anesthetic.samples.MCMCSamples(a, weights=weights, columns=paramNames, limits=limits)
fig, ax = samples.plot_2d(paramNames, types={'lower':'fastkde'}, levels=[0.68, 0.95], linestyles=['dashed', 'dotted'], lw=5)
plt.show()
```

**Expected behavior**
I would expect the n-th contour to be formatted with the n-th linestyle.

**Screenshots**
From the MWE:
![Figure_1](https://user-images.githubusercontent.com/40799217/124400231-dce6d100-dd18-11eb-95ce-401919e13b2f.png)

**Additional context**
I think this is related to this line in plot.py
```python
levels = iso_probability_contours(pdf, contours=levels)
```
which inverts the levels, and also adds a third level if two levels are given as an input. The inversion of levels makes sense (as `ax.contour` requires increasing levels, and [0.68, 0.95] C.L. correspond to [high, low] PDF values), but it messes with such arguments.

Suggested solution: Can we invert the `levels` input before passing it to `iso_probability_contours`? I.e. for the same result as above the input would need to be `[0.68, 0.95]`. Then levels should be consistent with other arguments. To avoid breaking changes we could check which order the user is using, currently the `levels` _must_ be increasing numbers (as they are not being inverted) and use that check to print a warning and adjust the behaviour.

**Comment by lukashergt** [comment]
I assume `linestyles=['dotted', 'dashed']` produces the desired outcome, right?

The problem here is that matplotlib's `(tri)contour(f)` require the `levels` to be put in in increasing order, i.e. lowest pdf value first. One of the guidelines for anesthetic is to try and match matplotlib's and pandas' behaviour as good as possible, such that using anesthetic should be fairly intuitive for people used to either of them. Hence, I would rather not go against the matplotlib behaviour here.

Now, I see how the inverse order of `levels` and `linestyles` in your example feels rather counterintuitive. I think this goes back to our decision to order what we initially called `contours` from 68% to 95%. Maybe it would be better to revert that and bring things more in line with the matplotlib behaviour and document the change accordingly in the docstring, something like "contours are ordered from outer to inner contours"... 

What would you think of that, @Stefan-Heimersheim?

**Comment by Stefan-Heimersheim** [comment]
> I assume linestyles=['dotted', 'dashed'] produces the desired outcome, right?

Yes indeed, forgot to mention that.

I see the analogy with matplotlib now; although "increasing levels of PDF" to "increasing confidence levels" doesn't seem like a perfect analogy (as they mean kind-of the opposite), but I get the idea from in "increasing numbers in the function argument" perspective.

> I think this goes back to our decision to order what we initially called contours from 68% to 95%. Maybe it would be better to revert that and bring things more in line with the matplotlib behaviour

Not sure I understand this correctly, what do you want to revert to?

**Comment by lukashergt** [comment]
> Not sure I understand this correctly, what do you want to revert to?

From
```python
samples.plot_2d(paramNames, levels=[0.68, 0.95], linestyles=['dashed', 'dotted'])
```
to
```python
samples.plot_2d(paramNames, levels=[0.95, 0.68], linestyles=['dashed', 'dotted'])
```
i.e. `levels` must always be ordered from outermost contour to innermost contour.

**Comment by Stefan-Heimersheim** [comment]
Yes I think that would be the clearer / simpler version -- we could suggest that version in the documentation; and if someone uses the old ("wrong") order we can just invert it and print a warning, to avoid breaking codes.
