### ISSUE TITLE
Use `\ln` instead of `\log` in the TEX label for log-evidence and similar

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#197]
Currently running `ns_output` will return an `MCMCSamples` instance with parameters `logZ`, `D`, and `d`. The TEX label for `logZ` is `$\log\mathcal{Z}$`. I'd like to propose changing the `\log` to `\ln`.

My reasoning for this TEX label change is that I prefer having the explicit `ln` when plotting or reporting specific values, such that it is absolutely clear what base is used for the logarithm. In purely theoretical equations I quite like the generic `log`, since there the base is typically irrelevant. 

This obviously comes down to taste, and I am happy to cede this point, if others don't like it. After all I can still change the label manually. But why not save that effort, should we agree on this.

**Comment by appetrosyan** [comment]
I use `ln` almost everywhere. Would like this change very much.

**Comment by williamjameshandley** [comment]
I was always taught to consider `log` equivalent to `ln`, but I have had enough emails over the years asking 'which log is "log Z"?', that I'm happy to go with a change to ln. Also approve of adding the average lnlikelihood to the array.

Any thoughts on whether we should keep the rather uninformative name `ns_output`? Perhaps there's a better name we could choose?

In the same PR we could also get in some more desiderata, in particular it would be good if `NestedSamples.logZ` returned a `DataFrame` or `MCMCSamples`, so that I could quickly compute `samples.logZ(1000).hist()` under the new plotting scheme #194.

It would also be good to add a logX function, which was attempted in #81, but never completed. This would be useful since it's somewhat unexpected that we often plot `logX` (e.g. in a higson plot/gui), but have no native functionality to do it (even though a `(-1/samples.nlive).cumsum()` is relatively straightforward).

**Comment by lukashergt** [comment]
This got resolved with #210.
