### ISSUE TITLE
 Change to reading system (#217) breaks reading polychord chains

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#226]
**Describe the bug**
As of commit `13c5624c8a81055064bd7e9f9f7789042aa4b021` "Change to reading system (#217)" the reading system seems broken, the [polychord quickstart example](https://github.com/PolyChord/PolyChordLite) does not work anymore.

**To Reproduce**
Use the [polychord quickstart example](https://github.com/PolyChord/PolyChordLite)
```bash
pip install git+https://github.com/williamjameshandley/anesthetic@13c5624c8a81055064bd7e9f9f7789042aa4b021
pip install git+https://github.com/PolyChord/PolyChordLite@master
wget https://raw.githubusercontent.com/PolyChord/PolyChordLite/master/run_pypolychord.py
python run_pypolychord.py
```
(also occurs with `@master`)

Versions before `13c5624c8a81055064bd7e9f9f7789042aa4b021` will produce a normal posterior plot, versions including and after `13c5624c8a81055064bd7e9f9f7789042aa4b021` produce an empty plot and the `samples` array is empty.

```python
In [1]: samples
Out[1]: 
Empty NestedSamples
Columns: []
Index: []
```

**Expected behavior**
Read samples, make plot.

**Additional information**
Found via bisect in [commit list](https://github.com/williamjameshandley/anesthetic/commits/master), these are the two neighboring versions that

* work: `pip install git+https://github.com/williamjameshandley/anesthetic@fdf6599a3f4cc76ea60d65f4cd7503f9e0bcee63`
* fail: `pip install git+https://github.com/williamjameshandley/anesthetic@13c5624c8a81055064bd7e9f9f7789042aa4b021` 

Edit: Had the wrong hash for the working commit earlier, I meant to paste `fdf6599a3f4cc76ea60d65f4cd7503f9e0bcee63`

Not sure if I am doing something stupid, I would be surprised if this is actually broken, but it's just the unmodified example.

**Comment by lukashergt** [comment]
Thanks for spotting this @Stefan-Heimersheim. Anesthetic is imminent to do it's major version jump, which will introduce many breaking changes. The new reading functionality is one of those breaking changes. Instead of
```python
samples = NestedSamples(root="my/file/root")
```
you now have to do
```python
samples = read_chains(root="my/file/root")
``` 
which is more consistent with Pandas' way of reading.

As such, this is a PolyChord issue, rather than an Anesthetic issue. But I think updates to other codes will have to wait for the last PRs in [milestone 2.0.0](https://github.com/williamjameshandley/anesthetic/milestone/5) to finish.

In the meantime it might be safer to not go bleeding edge with Anesthetic...

**Comment by Stefan-Heimersheim** [comment]
Oh of course, I didn't think of that! Thanks!
